# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            hyper-cube.io
tagline:          'We will find a way. We always have.'
description:      'Study the past if you would define the future.'
url:              http://hyper-cube.io
baseurl:          /

authors:
  jh:
    name: Jihoon Kim
    display_name: Jihoon
    email: jh.kim@hyper-cube.io
    web: http://ium.me
    twitter: _super_fishz
    github: super-fishz
  sh:
    name: Seungsoo Han
    display_name: Seungsoo
    github: hanseungsoo
    email: hss0417@gmail.com
  kwSeo:
    name: Kyeongwon Seo
    display_name: Kyeongwon Seo
    email: ruddnjs1230@gmail.com
    web: https://github.com/kwSeo
    github: kwSeo
  sy:
    name: Soonyoung Kim
    display_name: syKim
    email: tnsdud3506@naver.com
    github: rkdhs8
  hw:
    name: Hyewoon Na
    display_name: hwNa
    email: the7sunny@naver.com
    github: the7sunny

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hyper-cube-io/hyper-cube.io
